### PR TITLE
Work in progress: Add ability to link/unlink existing records

### PR DESCRIPTION
**Pull request by mlewis-everley**
This module works great, but you cannot link existing records (or unlink a record once linked).

This PR lays some of the groundwork, but I am am now kind of stuck...

Basically, the `GridFieldAddExistingAutoCompleter` and the new `GridFieldHasOneUnlinkButton` work, but they do not force the `GridField` to reload (or possibly, the `GridField` is not properly updated on reload).

I was wondering if you guys might have some insight? I am assuming you would like to add this functionality (to me it makes sense to be able to link/unlink as well as just add new)?

### CODE REVIEW

**Comment by hchokshi** [comment]
@mlewis-everley This package hasn't had a commit in quite a while, so I've created a fork that has some extra functionality and also merged in your PR with some refactoring at hchokshi/silverstripe-hasonefield.

It's marked as a composer replacement for this package under `3.x-dev` due to a couple of semver breaks.

**Comment by mlewis-everley** [comment]
@hchokshi, Cool! I have been meaning to look into this in more detail, so I will try and check it out ASAP.

I think this repo is low priority, but it is still maintained by @bummzack and @wilr (at least as far as I am aware). If your changes have finished off what I was doing, maybe you could submit a PR back to this repo and one of those guys might be able to merge it in?

**Comment by wilr** [comment]
@hchokshi long term did you want to PR your changes back here or do you want us to redirect this repo to your version?

**Comment by hchokshi** [comment]
@wilr  I'm happy to PR this back. There is a semver break in this commit - https://github.com/hchokshi/silverstripe-hasonefield/commit/b7033ed031a747a9c0339c5375db3cf35f8e605b

If you guys are OK with issuing a new major version with this change, I'll revert my composer vendor/replaces changes and PR this in?

**Comment by wilr** [comment]
Yep I'll tag a release prior to merge and start a new release line with your version.

**Comment by mlewis-everley** [comment]
Unfortunately I am still unable to get this PR request finished. @wilr (as you are about) any idea how I can make the parent EditForm reload after linking/unlinking an existing record?

**Comment by wilr** [comment]
Awesome work @hchokshi

**Comment by hchokshi** [comment]
Thanks @wilr. Also nice work @mlewis-everley 😃

**Pull request merged**
