### PR TITLE
Prevent breaking when $parent->$relationName returns null

### PR DESCRIPTION
**Pull request by jules0x**
Defensive check as it's possible to have an array at this point.

### CODE REVIEW

**Comment by wilr** [comment]
@jules0x What would be the case you get an array at this point?

**Comment by jules0x** [comment]
I think it's to do with requests from within the GridField, while the original fix this line was for seems to be related to requests from outside the GridField.

So in my case, the relationship was to 'Link', and what I saw was: 
```
LinkID: 3573
Link: GridState =
{"GridFieldAddRelation":null}
```

**Comment by wilr** [comment]
@jules0x Perhaps it's a case of the parent not existing in the database? Perhaps try at your code to check `$this->isInDb()`.

This needs a ModelClass to work so I'd imagine that this patch fixes the error but still the linking won't work as expected.

**Comment by adrexia** [comment]
@wilr This is for items that do exist in the db. This module is being used via the LinkField module, and is throwing errors when:

1. Inside an elemental area
2. There is a LinkField on the page
3. Trying to save

There's more to it than that, but I'm not sure what it is exactly.

$parent is what you'd expect it to be, and so is relation, but combining them as `$parent->$relationName`  makes it an array.

However, I noticed the error goes away when the code at the end is changed to this instead:
```
$model = call_user_func_array([$parent, $relationName], []);
$modelClass = $model->ClassName;
$this->setModelClass($modelClass);
```

Any idea why that would be?

**Comment by adrexia** [comment]
@wilr So, this also fixes it: ` $this->setModelClass(($parent->$relationName())->ClassName);` 
It looks like if its not explicitly looking for a method, it might find something else (a gridfield state array in this case). Is it worth pull requesting either of these alternatives?

**Comment by wilr** [comment]
Yep the second sounds more like a suitable fix. Also perhaps you may have some getter overriding your relationship if `$parent->$relationName())->ClassName` works but $parent->$relationName)->ClassName doesn't.

**Comment by wilr** [comment]
Yep the second sounds more like a suitable fix. Also perhaps you may have some getter overriding your relationship if `$parent->$relationName())->ClassName` works but $parent->$relationName)->ClassName doesn't.

**Pull request closed without merging**
